### ISSUE TITLE
License of Castle Combat

### ISSUE THREAD

**Issue by Trilarion** [karlb/castle-combat#1]
What is the code and artwork license of this game? Could license information be added to the repository?

**Comment by karlb** [comment]
You're right, I should add a proper License file. The first files are about twenty years old and I wasn't as careful about documenting licenses back then. But here's a rough summary:

Code and graphics: GPL (not the best fit for artwork, but I can relicense if necessary, since I did all of that myself)
Font: Public domain
Sound: I need to look that up

I'll add a file to the repo when I collected all the details. Do you have a specific use in mind?

**Comment by Trilarion** [comment]
Thanks for the reply. I mostly collect information about open source games (https://github.com/Trilarion/opensourcegames) so far, but later on maybe I want to contribute to some of them. The best is always if the license information is directly included in the repo. For artwork people usually use some kind of CC license.
